// Code generated by protoc-gen-go. DO NOT EDIT.
// source: workspace/workspace.proto

package workspace

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	_ "github.com/wxio/wxb/schemas/semantics"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WxbWorkspace struct {
	Module               *WxbWorkspace_Module    `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Require              []*WxbWorkspace_Require `protobuf:"bytes,2,rep,name=require,proto3" json:"require,omitempty"`
	Exclude              []*WxbWorkspace_Module  `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Replace              []*WxbWorkspace_Replace `protobuf:"bytes,4,rep,name=replace,proto3" json:"replace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WxbWorkspace) Reset()         { *m = WxbWorkspace{} }
func (m *WxbWorkspace) String() string { return proto.CompactTextString(m) }
func (*WxbWorkspace) ProtoMessage()    {}
func (*WxbWorkspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b0f3b2dfd43c27, []int{0}
}

func (m *WxbWorkspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbWorkspace.Unmarshal(m, b)
}
func (m *WxbWorkspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbWorkspace.Marshal(b, m, deterministic)
}
func (m *WxbWorkspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbWorkspace.Merge(m, src)
}
func (m *WxbWorkspace) XXX_Size() int {
	return xxx_messageInfo_WxbWorkspace.Size(m)
}
func (m *WxbWorkspace) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbWorkspace.DiscardUnknown(m)
}

var xxx_messageInfo_WxbWorkspace proto.InternalMessageInfo

func (m *WxbWorkspace) GetModule() *WxbWorkspace_Module {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *WxbWorkspace) GetRequire() []*WxbWorkspace_Require {
	if m != nil {
		return m.Require
	}
	return nil
}

func (m *WxbWorkspace) GetExclude() []*WxbWorkspace_Module {
	if m != nil {
		return m.Exclude
	}
	return nil
}

func (m *WxbWorkspace) GetReplace() []*WxbWorkspace_Replace {
	if m != nil {
		return m.Replace
	}
	return nil
}

//
type WxbWorkspace_Module struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxbWorkspace_Module) Reset()         { *m = WxbWorkspace_Module{} }
func (m *WxbWorkspace_Module) String() string { return proto.CompactTextString(m) }
func (*WxbWorkspace_Module) ProtoMessage()    {}
func (*WxbWorkspace_Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b0f3b2dfd43c27, []int{0, 0}
}

func (m *WxbWorkspace_Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbWorkspace_Module.Unmarshal(m, b)
}
func (m *WxbWorkspace_Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbWorkspace_Module.Marshal(b, m, deterministic)
}
func (m *WxbWorkspace_Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbWorkspace_Module.Merge(m, src)
}
func (m *WxbWorkspace_Module) XXX_Size() int {
	return xxx_messageInfo_WxbWorkspace_Module.Size(m)
}
func (m *WxbWorkspace_Module) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbWorkspace_Module.DiscardUnknown(m)
}

var xxx_messageInfo_WxbWorkspace_Module proto.InternalMessageInfo

func (m *WxbWorkspace_Module) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WxbWorkspace_Module) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type WxbWorkspace_Require struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Indirect             bool     `protobuf:"varint,3,opt,name=indirect,proto3" json:"indirect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxbWorkspace_Require) Reset()         { *m = WxbWorkspace_Require{} }
func (m *WxbWorkspace_Require) String() string { return proto.CompactTextString(m) }
func (*WxbWorkspace_Require) ProtoMessage()    {}
func (*WxbWorkspace_Require) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b0f3b2dfd43c27, []int{0, 1}
}

func (m *WxbWorkspace_Require) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbWorkspace_Require.Unmarshal(m, b)
}
func (m *WxbWorkspace_Require) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbWorkspace_Require.Marshal(b, m, deterministic)
}
func (m *WxbWorkspace_Require) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbWorkspace_Require.Merge(m, src)
}
func (m *WxbWorkspace_Require) XXX_Size() int {
	return xxx_messageInfo_WxbWorkspace_Require.Size(m)
}
func (m *WxbWorkspace_Require) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbWorkspace_Require.DiscardUnknown(m)
}

var xxx_messageInfo_WxbWorkspace_Require proto.InternalMessageInfo

func (m *WxbWorkspace_Require) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *WxbWorkspace_Require) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *WxbWorkspace_Require) GetIndirect() bool {
	if m != nil {
		return m.Indirect
	}
	return false
}

type WxbWorkspace_Replace struct {
	Old                  *WxbWorkspace_Module `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New                  *WxbWorkspace_Module `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WxbWorkspace_Replace) Reset()         { *m = WxbWorkspace_Replace{} }
func (m *WxbWorkspace_Replace) String() string { return proto.CompactTextString(m) }
func (*WxbWorkspace_Replace) ProtoMessage()    {}
func (*WxbWorkspace_Replace) Descriptor() ([]byte, []int) {
	return fileDescriptor_65b0f3b2dfd43c27, []int{0, 2}
}

func (m *WxbWorkspace_Replace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbWorkspace_Replace.Unmarshal(m, b)
}
func (m *WxbWorkspace_Replace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbWorkspace_Replace.Marshal(b, m, deterministic)
}
func (m *WxbWorkspace_Replace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbWorkspace_Replace.Merge(m, src)
}
func (m *WxbWorkspace_Replace) XXX_Size() int {
	return xxx_messageInfo_WxbWorkspace_Replace.Size(m)
}
func (m *WxbWorkspace_Replace) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbWorkspace_Replace.DiscardUnknown(m)
}

var xxx_messageInfo_WxbWorkspace_Replace proto.InternalMessageInfo

func (m *WxbWorkspace_Replace) GetOld() *WxbWorkspace_Module {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *WxbWorkspace_Replace) GetNew() *WxbWorkspace_Module {
	if m != nil {
		return m.New
	}
	return nil
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*WxbWorkspace)(nil),
	Field:         50000,
	Name:          "workspace.file",
	Tag:           "bytes,50000,opt,name=file",
	Filename:      "workspace/workspace.proto",
}

func init() {
	proto.RegisterType((*WxbWorkspace)(nil), "workspace.WxbWorkspace")
	proto.RegisterType((*WxbWorkspace_Module)(nil), "workspace.WxbWorkspace.Module")
	proto.RegisterType((*WxbWorkspace_Require)(nil), "workspace.WxbWorkspace.Require")
	proto.RegisterType((*WxbWorkspace_Replace)(nil), "workspace.WxbWorkspace.Replace")
	proto.RegisterExtension(E_File)
}

func init() { proto.RegisterFile("workspace/workspace.proto", fileDescriptor_65b0f3b2dfd43c27) }

var fileDescriptor_65b0f3b2dfd43c27 = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x86, 0x43, 0x21, 0xd0, 0x4e, 0xef, 0x6a, 0x36, 0x77, 0x4a, 0x6e, 0xae, 0xc4, 0xc4, 0xd8,
	0x15, 0x98, 0xba, 0x51, 0x17, 0x5d, 0x74, 0xe1, 0xc6, 0x18, 0x93, 0xd9, 0x34, 0x71, 0x07, 0xc3,
	0x69, 0x3b, 0x11, 0x18, 0x9c, 0x01, 0xe1, 0x09, 0x7c, 0x00, 0x9f, 0xc5, 0x07, 0xf1, 0x79, 0x5c,
	0x19, 0x86, 0x42, 0x8d, 0x49, 0x6d, 0x77, 0x73, 0xce, 0xf9, 0xfe, 0xff, 0xe7, 0x84, 0x83, 0x26,
	0x95, 0x90, 0x4f, 0x2a, 0x0f, 0x19, 0x04, 0xfd, 0xcb, 0xcf, 0xa5, 0x28, 0x04, 0x1e, 0xf5, 0x0d,
	0xd7, 0x5b, 0x0b, 0xb1, 0x4e, 0x20, 0xd0, 0x83, 0xa8, 0x5c, 0x05, 0x31, 0x28, 0x26, 0x79, 0x5e,
	0x08, 0xd9, 0xc2, 0xee, 0x44, 0x41, 0x1a, 0x66, 0x05, 0x67, 0x2a, 0xe8, 0x5f, 0xed, 0xe8, 0xf4,
	0xcd, 0x42, 0x7f, 0x96, 0x75, 0xb4, 0xec, 0xdc, 0xf0, 0x1c, 0xd9, 0xa9, 0x88, 0xcb, 0x04, 0x88,
	0xe1, 0x19, 0xd3, 0xf1, 0xec, 0xbf, 0xbf, 0x8b, 0xfe, 0x0e, 0xfa, 0xf7, 0x9a, 0x5a, 0xd8, 0x9f,
	0xef, 0x64, 0x30, 0x34, 0xe8, 0x56, 0x85, 0xaf, 0x91, 0x23, 0xe1, 0xb9, 0xe4, 0x12, 0xc8, 0xc0,
	0x33, 0xa7, 0xe3, 0xd9, 0xc9, 0x3e, 0x03, 0xda, 0x62, 0xb4, 0xe3, 0xf1, 0x15, 0x72, 0xa0, 0x66,
	0x49, 0x19, 0x03, 0x31, 0xb5, 0xf4, 0x40, 0x36, 0xed, 0xf0, 0x36, 0x34, 0x4f, 0x42, 0x06, 0xc4,
	0x3a, 0x14, 0xaa, 0x31, 0xda, 0xf1, 0xee, 0x1c, 0xd9, 0xad, 0x1b, 0x76, 0x91, 0x95, 0x87, 0xc5,
	0x46, 0xef, 0x3d, 0xea, 0xf7, 0xd2, 0x3d, 0x4c, 0x90, 0xf3, 0x02, 0x52, 0x71, 0x91, 0x91, 0x41,
	0x33, 0xa6, 0x5d, 0xe9, 0x32, 0xe4, 0x6c, 0x17, 0xf9, 0xd5, 0xc0, 0xfb, 0x61, 0xd0, 0x8f, 0xbb,
	0x36, 0x76, 0xd1, 0x90, 0x67, 0x31, 0x97, 0xc0, 0x0a, 0x62, 0x7a, 0xc6, 0x74, 0x48, 0xfb, 0xda,
	0x4d, 0x9b, 0x10, 0xfd, 0xbd, 0xf8, 0x02, 0x99, 0x22, 0x89, 0x8f, 0xfb, 0x39, 0xb4, 0x41, 0x1b,
	0x45, 0x06, 0x95, 0x8e, 0x3d, 0x42, 0x91, 0x41, 0x75, 0x73, 0x87, 0xac, 0x15, 0x4f, 0x00, 0xff,
	0xf3, 0xdb, 0xd3, 0xf2, 0xbb, 0xd3, 0xf2, 0x6f, 0x79, 0x02, 0x0f, 0x79, 0xc1, 0x45, 0xa6, 0xc8,
	0xc7, 0xab, 0xa9, 0x2d, 0xff, 0xee, 0xb1, 0xa4, 0xda, 0x64, 0x71, 0xfe, 0x78, 0xb6, 0xe6, 0xc5,
	0xa6, 0x8c, 0x7c, 0x26, 0xd2, 0xa0, 0xaa, 0xb9, 0x08, 0xaa, 0x3a, 0x0a, 0x14, 0xdb, 0x40, 0x1a,
	0xaa, 0xdd, 0x61, 0x47, 0xb6, 0x4e, 0xb9, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x15, 0x60,
	0x9f, 0xf6, 0x02, 0x00, 0x00,
}
