// Code generated by protoc-gen-go. DO NOT EDIT.
// source: semantics/semantics.proto

package semantics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WxbSchemaFile struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxbSchemaFile) Reset()         { *m = WxbSchemaFile{} }
func (m *WxbSchemaFile) String() string { return proto.CompactTextString(m) }
func (*WxbSchemaFile) ProtoMessage()    {}
func (*WxbSchemaFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3243c923cfe81ad, []int{0}
}

func (m *WxbSchemaFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbSchemaFile.Unmarshal(m, b)
}
func (m *WxbSchemaFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbSchemaFile.Marshal(b, m, deterministic)
}
func (m *WxbSchemaFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbSchemaFile.Merge(m, src)
}
func (m *WxbSchemaFile) XXX_Size() int {
	return xxx_messageInfo_WxbSchemaFile.Size(m)
}
func (m *WxbSchemaFile) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbSchemaFile.DiscardUnknown(m)
}

var xxx_messageInfo_WxbSchemaFile proto.InternalMessageInfo

type WxbSchemaField struct {
	Manditory            bool     `protobuf:"varint,1,opt,name=manditory,proto3" json:"manditory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxbSchemaField) Reset()         { *m = WxbSchemaField{} }
func (m *WxbSchemaField) String() string { return proto.CompactTextString(m) }
func (*WxbSchemaField) ProtoMessage()    {}
func (*WxbSchemaField) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3243c923cfe81ad, []int{1}
}

func (m *WxbSchemaField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxbSchemaField.Unmarshal(m, b)
}
func (m *WxbSchemaField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxbSchemaField.Marshal(b, m, deterministic)
}
func (m *WxbSchemaField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxbSchemaField.Merge(m, src)
}
func (m *WxbSchemaField) XXX_Size() int {
	return xxx_messageInfo_WxbSchemaField.Size(m)
}
func (m *WxbSchemaField) XXX_DiscardUnknown() {
	xxx_messageInfo_WxbSchemaField.DiscardUnknown(m)
}

var xxx_messageInfo_WxbSchemaField proto.InternalMessageInfo

func (m *WxbSchemaField) GetManditory() bool {
	if m != nil {
		return m.Manditory
	}
	return false
}

var E_File = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*WxbSchemaFile)(nil),
	Field:         49999,
	Name:          "semantics.file",
	Tag:           "bytes,49999,opt,name=file",
	Filename:      "semantics/semantics.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*WxbSchemaField)(nil),
	Field:         49999,
	Name:          "semantics.field",
	Tag:           "bytes,49999,opt,name=field",
	Filename:      "semantics/semantics.proto",
}

func init() {
	proto.RegisterType((*WxbSchemaFile)(nil), "semantics.WxbSchemaFile")
	proto.RegisterType((*WxbSchemaField)(nil), "semantics.WxbSchemaField")
	proto.RegisterExtension(E_File)
	proto.RegisterExtension(E_Field)
}

func init() { proto.RegisterFile("semantics/semantics.proto", fileDescriptor_c3243c923cfe81ad) }

var fileDescriptor_c3243c923cfe81ad = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x4e, 0xcd, 0x4d,
	0xcc, 0x2b, 0xc9, 0x4c, 0x2e, 0xd6, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38,
	0xe1, 0x02, 0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x89, 0xa4, 0xd2, 0x34,
	0xfd, 0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0xfc, 0x22, 0x88, 0x62, 0x25, 0x7e, 0x2e,
	0xde, 0xf0, 0x8a, 0xa4, 0xe0, 0xe4, 0x8c, 0xd4, 0xdc, 0x44, 0xb7, 0xcc, 0x9c, 0x54, 0x25, 0x3d,
	0x2e, 0x3e, 0x24, 0x81, 0xd4, 0x9c, 0x14, 0x21, 0x19, 0x2e, 0xce, 0xdc, 0xc4, 0xbc, 0x94, 0xcc,
	0x92, 0xfc, 0xa2, 0x4a, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x84, 0x80, 0x95, 0x0f, 0x17,
	0x4b, 0x5a, 0x66, 0x4e, 0xaa, 0x90, 0x8c, 0x1e, 0xc4, 0x2e, 0x3d, 0x98, 0x5d, 0x7a, 0x20, 0xe3,
	0xfc, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x8a, 0x25, 0xce, 0xb7, 0x31, 0x2b, 0x30, 0x6a, 0x70, 0x1b,
	0x49, 0xe8, 0x21, 0x5c, 0x8b, 0x62, 0x6f, 0x10, 0xd8, 0x14, 0xab, 0x00, 0x2e, 0xd6, 0x34, 0xb0,
	0xa5, 0xb2, 0x58, 0x8c, 0x4b, 0xcd, 0x49, 0x41, 0x37, 0x4f, 0x12, 0xbb, 0x79, 0xa9, 0x39, 0x29,
	0x41, 0x10, 0x83, 0x9c, 0x0c, 0xa2, 0xf4, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3,
	0x73, 0xf5, 0xcb, 0x2b, 0x32, 0xf3, 0xf5, 0xcb, 0x2b, 0x92, 0xf4, 0x33, 0xf3, 0x4a, 0x52, 0x8b,
	0xf2, 0x12, 0x73, 0xf4, 0x8b, 0xc1, 0x5a, 0x90, 0x42, 0x31, 0x89, 0x0d, 0x6c, 0xa5, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x61, 0x56, 0xe4, 0x51, 0x63, 0x01, 0x00, 0x00,
}
